### ISSUE TITLE
Cache - Filewatcher 

### ISSUE THREAD

**Issue by stuartshay** [stuartshay/MicroService#270]
**Pull From Develop Branch**
PR's Merge in **Develop** Not Master

Tools: https://www.funduc.com/fstouch.htm
This will change the file name DateTimeStamp

- [x] 1  Semantic Logging (See Cache Reset) on All Methods 

- [x] 2 Changing the DateTime Stamp Does not Activate the Cache Reload

**Comment by TerraVenil** [comment]
![image](https://user-images.githubusercontent.com/6068068/113565693-1756aa00-9614-11eb-9624-3def320218f8.png)

**Comment by stuartshay** [comment]
Updated the Logging, I think the way I did will make it easier to query. Do a Pull of latest in branch, will document more issues

**Comment by stuartshay** [comment]
Done
