### ISSUE TITLE
Health Checks 

### ISSUE THREAD

**Issue by stuartshay** [stuartshay/MicroService#272]
Health Check Dashboard
http://localhost:5000/health-ui#/healthchecks

![image](https://user-images.githubusercontent.com/887805/113649113-da160a80-965b-11eb-8a9f-f336af4c24ed.png)

#### Implemented Examples

Examples
https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks

Some ways to implement Health Check
https://github.com/stuartshay/AzureDevOpsKats/tree/master/src/AzureDevOpsKats.Common/HealthChecks

- [x] 1 Implement ShapeRootDirectory Health Check 

Purpose:  The **ShapeRootDirectory** in Production most likely will use a NFS Unix Mount,
Need to Determine if Directory Exists 

There are some built in checks that might be able to accomplish this

See
https://github.com/stuartshay/MicroService/blob/a203ca054d47fa5c017655ec4e2b2e566b1c571a/src/MicroService.WebApi/Extensions/ServiceCollectionExtensions.cs#L114

- [x] 2 Health Check on InMemoryCache Service

Need a Health Check to Determine is the Background Service is in Started State.

Service will FAIL if the **NOT** ShapeRootFileExists 
Service will FAIL if *.dbf file is **corrupted** and unable to load

**How do I implement .NET Core Health Checks on a Hosted Service?**
https://stackoverflow.com/questions/60449633/how-do-i-implement-net-core-health-checks-on-a-hosted-service

Monitoring Health of ASP.NET Core Background Services With TCP Probes on Kubernetes
https://dzone.com/articles/monitoring-health-of-aspnet-core-background-servic

Example (Maybe Usefull)
https://gist.github.com/CarlosLanderas/d62e3b21d27c9cece31fe147bed467c9#file-program-cs-L83

**Comment by TerraVenil** [comment]
![image](https://user-images.githubusercontent.com/6068068/113722130-ce2c5600-96f8-11eb-81c3-f7026b7c1614.png)

**Comment by stuartshay** [comment]
Updated Branch 
Still need to test using Docker, Changes do work locally
